name: Build and deploy docker image on release

on:
  push:
    tags: ['*']

env:
  REGISTRY: ghcr.io

concurrency:
  group: manga-notify-production
  cancel-in-progress: false

jobs:
  deployment:
    environment: yc-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Lower case image name
        run: |
          echo "IMAGE_NAME=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: ${{ github.repository }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Copy deployment configuration
        uses: appleboy/scp-action@v0.1.7
        with:
          host: sakura.isthisloss.ru
          username: manga-notify
          key: ${{ secrets.KEY }}
          port: 22
          source: "docs/deploy/*"
          target: /home/manga-notify/app
          strip_components: 2

      - name: Deploy image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: sakura.isthisloss.ru
          username: manga-notify
          key: ${{ secrets.KEY }}
          port: 22
          envs: TAG
          script: bash /home/manga-notify/app/deploy.sh
        env:
          TAG: ${{ github.ref_name }}
